### ISSUE TITLE
 Invalid hook call. Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by SergioGeeK7** [nas5w/use-local-storage#10]
**Describe the bug**
Following error message it's displayed in the browser

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

**To Reproduce**
use the react hook on any component

**Expected behavior**
Should work properly without forcing to use rect 17, react hooks works from React 16.8

**Additional context**
Similar libraries does not list `react` as a dependency, I wonder if that's a best practice

https://www.npmjs.com/package/@rooks/use-localstorage
https://www.npmjs.com/package/react-use-localstorage

**Comment by nas5w** [comment]
This should be fixed in the newest version, 2.1.1, thank you for reporting the issue!

**Comment by SergioGeeK7** [comment]
oww, that was fast, thank you !
