### ISSUE TITLE
SSR Framework says window is undefined

### ISSUE THREAD

**Issue by stackoverprof** [nas5w/use-local-storage#18]
**Describe the bug**
I'm using this on Next.js and it seems that window is called when it wasn't ready in the Next.js's server environment/build time

**To Reproduce**
just install and use it on nextjs (or anything with ssr/ssg method)

**Expected behavior**
I think you can prevent calling before windows object is ready, something like : if (window) 

**Screenshots**
[https://ibb.co/4Jvw0j9](url) 
https://ibb.co/4Jvw0j9

**Comment by stackoverprof** [comment]
![screenshot](https://i.ibb.co/DLcPj7s/Screen-Shot-2021-11-18-at-20-00-54.png "Text to show on mouseover")

**Comment by stackoverprof** [comment]
Well this workaround work form me and typescript

`import _useLocalStorage from 'use-local-storage';

type ProductTuple<T> = [
	state: T,
	setState: ((newState: (prevState: T) => T) => void) & ((newState: T) => void)
];

export const useLocalStorage = <T>(key: string, initial: T): ProductTuple<T> => {
	if (typeof window === 'undefined') return [initial, () => undefined];
	else return _useLocalStorage<T>(key, initial);
};
`

**Comment by nas5w** [comment]
Closed by #20
