### ISSUE TITLE
Remove key when setting value to undefined

### ISSUE THREAD

**Issue by franciscohanna92** [nas5w/use-local-storage#19]
I'm expecting that a key I've setted with a value of `undefined` to be removed from the localStorage.

Give the following:
```javascript
import useLocalStorage from "use-local-storage";

function App() {
  const [username, setUsername] = useLocalStorage("name", "");

  return (
    <>
      <input
        value={username}
        onChange={(e) => {
          setUsername(e.target.value);
        }}
      />
    <button onClick={() => setUsername(undefined)}>Clear localStorage</button>
    </>
  );
}
```

Once I click the "Clear localStorage" button, I expect the "name" key to be removed from the local storage. The observed result is that the `name` key gets the value `undefined` in the storage.

![image](https://user-images.githubusercontent.com/12707758/144276447-e9155e19-8f55-4048-8b0a-4cc5425e9e72.png)

[Here's a Codesandbox](https://codesandbox.io/s/use-local-storage-clear-state-qk1ms?file=/src/App.js) that reproduces this behavior.

**Comment by atifcppprogrammer** [comment]
Hi there @nas5w @franciscohanna92  ! I am a new contributor here would you like to assign this issue to me ?

**Comment by nas5w** [comment]
@atifcppprogrammer that sounds like a good solution! Would love to see a PR for this (with tests + docs updated). Thank you!

**Comment by atifcppprogrammer** [comment]
@nas5w thanks a million 👍 I will work on this over the weekend 👨‍💻 , will get you that pull request next week 📆, sound good 🧐 ?

**Comment by atifcppprogrammer** [comment]
@nas5w so just so we are clear on this, if we are targeting the following implementation 
```jsx
import useLocalStorage from "use-local-storage";
function App() {
  const [username, setUsername, unsetUsername] = useLocalStorage("name", "");

  return (
    <>
      <input
        value={username}
        onChange={(e) => {
          setUsername(e.target.value);
        }}
      />
      {/* removing the value set against the key "username" from localStorage */}
      <button onClick={() => unsetUsername()}>
        Clear localStorage
      </button>
    </>
  );
}
```
will ```setUsername(undefined)``` preserve the current behavior i.e it will set value against the key "name" in localStorage to "undefined" or should it be removed from localStorage as @franciscohanna92 has indicated in the original comment.

**Comment by nas5w** [comment]
@atifcppprogrammer let's just add the third function to the array as you first proposed. I don't want to change the current behavior of the state-setter because then there'd be _no_ way to set the key to `undefined` if that was the desired outcome.

**Comment by franciscohanna92** [comment]
> there'd be no way to set the key to undefined if that was the desired outcome

The outcome for `setUsername(undefined)` is the key to be set with the string `"undefined"`. IMO, this is not predictable because the key doesn't get the value `undefined` but a string. It could always be accomplished by calling `setUsername("undefined")`, but I'm not sure why anyone would be doing such thing. 

At the same time, removing the key is a breaking change: I imagine there are some folks out there doing something like `if (username === "undefined")` given the current implementation.

**Comment by franciscohanna92** [comment]
@nas5w 

> there'd be no way to set the key to undefined if that was the desired outcome

The outcome for `setUsername(undefined)` is the key to be set with the string `"undefined"` and not `undefined` as it should be expected. Anyway, it could always be accomplished by calling `setUsername("undefined")`, which would have a predictable outome.

At the same time, removing the key when setting it to `undefined` is a breaking change: I imagine there are some folks out there doing something like `if (username === "undefined")` given the current implementation.

**Comment by nas5w** [comment]
Thanks for chiming in @franciscohanna92!

@atifcppprogrammer since `undefined` is actually being stored as a string in local storage, I'm now starting to think we should go with what @franciscohanna92 initially suggested: if the user sets the item to `undefined`, the key is removed from local storage. Sorry to ask you to rework the PR you already have, but I think it's best to do it this way (plus it should be easier).

**Comment by atifcppprogrammer** [comment]
> Thanks for chiming in @franciscohanna92!
> 
> @atifcppprogrammer since `undefined` is actually being stored as a string in local storage, I'm now starting to think we should go with what @franciscohanna92 initially suggested: if the user sets the item to `undefined`, the key is removed from local storage. Sorry to ask you to rework the PR you already have, but I think it's best to do it this way (plus it should be easier).

Hey @nas5w no problem, so given this new specification there won't be any need for the hook to provide the third remove function as well I imagine.

**Comment by nas5w** [comment]
@atifcppprogrammer exactly. I think this will be a better solution

**Comment by atifcppprogrammer** [comment]
Hi @nas5w please find the PR for above discussed specification.

**Comment by atifcppprogrammer** [comment]
So @nas5w does the current PR need any further changes ?

**Comment by nas5w** [comment]
@atifcppprogrammer will finish my review this weekend. Thank you!

**Comment by atifcppprogrammer** [comment]
@nas5w, noticed a small typo in the README.md, corrected it !
